apiVersion: apps/v1
kind: Deployment
metadata:
  name: genius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genius
  template:
    metadata:
      labels:
        app: genius
    spec:
      containers:
      - image: okteto.dev/genius:latest
        name: genius
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "56956827-9c9c-4e0b-9ff2-98abd4160d6a"
        - name: Vless_Path
          value: "/56956827-9c9c-4e0b-9ff2-98abd4160d6a"
        - name: Vmess_UUID
          value: "46b4f13d-79a5-4156-9c1a-c918f5314b49"
        - name: Vmess_Path
          value: "/46b4f13d-79a5-4156-9c1a-c918f5314b49"
        - name: Share_Path
          value: "/Share039"
